name: swn_play
description: Application for SWN Play
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  appcheck: ^1.0.6
  dio: ^5.2.0+1
  permission_handler: ^10.3.0
  app_installer: ^1.1.0
  flutter_markdown: ^0.6.15
  url_launcher: ^6.1.11
  intl: ^0.18.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true